export const STOCKS = [
  {
    sym: 'NVDA',
    name: 'Nvidia Corp',
    sector: 'Semiconductors',
    cik: '0001045810',
    basePrice: 875.20,
    vol: 0.025,
    // What retail sees — always bullish analyst consensus
    analystNote: 'GPU demand remains robust heading into Q3. Data centre capex accelerating. Reiterate Buy.',
    eps: '$5.58',
    priceTarget: '$1,050',
    // What the alternative data says — hedge fund only
    altDataDir: 'bear' as const,
    result: -0.14,
    resultNote: 'MISS — EPS $4.82 vs $5.58 est. Stock -14%.',
    hedgeAction: 'Shorted based on satellite car park data and job posting velocity down 34% YoY.',
    // Search terms for Google Trends proxy via news volume
    searchTerms: ['NVIDIA GPU', 'CUDA', 'data center AI'],
  },
  {
    sym: 'AAPL',
    name: 'Apple Inc',
    sector: 'Consumer Tech',
    cik: '0000320193',
    basePrice: 189.50,
    vol: 0.015,
    analystNote: 'iPhone 16 cycle showing strong early demand signals. Services revenue accelerating. Buy.',
    eps: '$1.46',
    priceTarget: '$230',
    altDataDir: 'bull' as const,
    result: 0.08,
    resultNote: 'BEAT — EPS $1.61 vs $1.46 est. Stock +8%.',
    hedgeAction: 'Went long — CC spend data confirmed analyst consensus. High conviction.',
    searchTerms: ['iPhone', 'Apple Store', 'iOS'],
  },
  {
    sym: 'TSLA',
    name: 'Tesla Inc',
    sector: 'EV / Auto',
    cik: '0001318605',
    basePrice: 242.30,
    vol: 0.032,
    analystNote: 'Cybertruck ramp accelerating into H2. Margin recovery expected. Reiterate Buy.',
    eps: '$0.72',
    priceTarget: '$300',
    altDataDir: 'bear' as const,
    result: -0.11,
    resultNote: 'MISS — EPS $0.58 vs $0.72 est. Stock -11%.',
    hedgeAction: 'Shorted — job posting velocity down 42% YoY signals headcount freeze and slowing ramp.',
    searchTerms: ['Tesla Model 3', 'Tesla delivery', 'Cybertruck'],
  },
  {
    sym: 'META',
    name: 'Meta Platforms',
    sector: 'Social Media',
    cik: '0001326801',
    basePrice: 512.80,
    vol: 0.020,
    analystNote: 'Reels monetisation inflecting. Ad revenue re-acceleration underway. Strong Buy.',
    eps: '$5.12',
    priceTarget: '$600',
    altDataDir: 'bull' as const,
    result: 0.12,
    resultNote: 'BEAT — EPS $5.71 vs $5.12 est. Stock +12%.',
    hedgeAction: 'Went long — CC spend on Meta advertising surged 22% MoM. Data confirmed bull case.',
    searchTerms: ['Facebook ads', 'Instagram', 'Meta Quest'],
  },
  {
    sym: 'JPM',
    name: 'JPMorgan Chase',
    sector: 'Financials',
    cik: '0000019617',
    basePrice: 198.40,
    vol: 0.012,
    analystNote: 'NIM stabilising. Investment banking recovery underway. Loan book quality solid. Buy.',
    eps: '$4.18',
    priceTarget: '$230',
    altDataDir: 'neut' as const,
    result: 0.03,
    resultNote: 'INLINE — EPS $4.26 vs $4.18 est. Stock +3%.',
    hedgeAction: 'Held neutral — alt data mixed. No strong directional signal. Avoided the name.',
    searchTerms: ['JPMorgan banking', 'Chase bank', 'investment banking'],
  },
  {
    sym: 'AMZN',
    name: 'Amazon.com',
    sector: 'E-Commerce / Cloud',
    cik: '0001018724',
    basePrice: 182.60,
    vol: 0.022,
    analystNote: 'AWS growth re-accelerating. Advertising business showing strength. Outperform.',
    eps: '$1.03',
    priceTarget: '$220',
    altDataDir: 'bull' as const,
    result: 0.09,
    resultNote: 'BEAT — EPS $1.19 vs $1.03 est. Stock +9%.',
    hedgeAction: 'Went long — shipping volumes +31% vs estimate. AWS hiring up 28% YoY.',
    searchTerms: ['Amazon Prime', 'AWS cloud', 'Amazon delivery'],
  },
]

export type Stock = typeof STOCKS[0]
export type AltDataDir = 'bull' | 'bear' | 'neut'
